name = "cipherstash-demo"
workers_dev = true
compatibility_date = "2022-01-20"
main = "build/worker/shim.mjs"

[vars]
WORKERS_RS_VERSION = "0.0.10"
CIPHERSTASH_HOST = "https://ap-southeast-2.aws.stashdata.net"

[build]
command = "cargo install -q worker-build && worker-build --release"
